# Generated by Django 4.0.1 on 2022-02-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_price',
        ),
    ]
