products = [
    {
      '_id': '1',
      'name': 'MSI PCI-Ex GeForce RTX 3060 Ti Gaming',
      'image': '/images/MSI PCI-Ex GeForce RTX 3060 Ti Gaming.jpg',
      'description':
        'The GeForce RTX™ 3060 Ti lets you take on the latest games using the power of Ampere—NVIDIA’s 2nd generation RTX architecture. Get incredible performance with enhanced Ray Tracing Cores and Tensor Cores, new streaming multiprocessors, and high-speed G6 memory.',
      'brand': 'MSI',
      'category': 'Electronics',
      'price': 89.99,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'MSI PCI-Ex GeForce RTX 3070 Gaming Trio',
      'image': '/images/MSI PCI-Ex GeForce RTX 3070 Gaming Trio 8GB.jpg',
      'description':
        'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
      'brand': 'MSI',
      'category': 'Electronics',
      'price': 599.99,
      'countInStock': 0,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'MSI PCI-Ex GeForce RTX 3070 Gaming',
      'image': '/images/MSI PCI-Ex GeForce RTX 3070 Gaming.jpg',
      'description':
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
      'brand': 'MSI',
      'category': 'Electronics',
      'price': 929.99,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'MSI PCI-Ex GeForce RTX 3070 SUPRIM 8G ',
      'image': '/images/MSI PCI-Ex GeForce RTX 3070 SUPRIM 8G .jpg',
      'description':
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
      'brand': 'MSI',
      'category': 'Electronics',
      'price': 399.99,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'MSI PCI-Ex GeForce RTX 3070 Ti VENTUS',
      'image': '/images/MSI PCI-Ex GeForce RTX 3070 Ti VENTUS 3X 8G.jpg',
      'description':
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
      'brand': 'MSI',
      'category': 'Electronics',
      'price': 49.99,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'MSI PCI-Ex GeForce RTX 3070 VENTUS',
      'image': '/images/MSI PCI-Ex GeForce RTX 3070 VENTUS.jpg',
      'description':
        'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
      'brand': 'MSI',
      'category': 'Electronics',
      'price': 29.99,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
  ]
